
global proc AEalInputVectorTemplate(string $n)
{
	editorTemplate -beginScrollLayout;
	AEswatchDisplay $n;
	
	editorTemplate -addControl "input";
	editorTemplate -addControl "userName";
	editorTemplate -label "Custom" -addControl "vector";
	editorTemplate -addControl "type";
	
	editorTemplate -beginLayout "Transform";
		editorTemplate -addControl "matrix";
	editorTemplate -endLayout;

	editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
