source "alRemap.mel";

global proc AEalBlackbodyTemplate(string $n)
{
	editorTemplate -beginScrollLayout;
	AEswatchDisplay $n;
	
	editorTemplate -addControl "temperature";
	editorTemplate -addControl "strength";
	
	editorTemplate -beginLayout "Advanced";
	
	editorTemplate -addControl "physicalIntensity";
	editorTemplate -addControl "physicalExposure";
	
	editorTemplate -endLayout;

	editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}
