global proc AEalCombineColorTemplate(string $n)
{
	editorTemplate -beginScrollLayout;
	AEswatchDisplay $n;
	
	editorTemplate  -label "Input 1" -addControl "input1";
	editorTemplate  -label "Input 2" -addControl "input2";
	editorTemplate  -label "Input 3" -addControl "input3";
	editorTemplate  -label "Operation" -addControl "combineOp";

	
	editorTemplate -addExtraControls;
	
	editorTemplate -endScrollLayout;
}
